### ISSUE TITLE
Add Classes

### ISSUE THREAD

**Issue by Stefhu67** [navylemdi/AnamorphosePlane#1]
Hey,

I think you should add some classes to make the package more oriented object programming.
For instance, you can create different objects:
- image: that contains the information of the speckle sheet, 
- camera: that contains the information of the focal length, angle of view etc...
- object (the wing in this case): that contains the position of this one to the cameras

After that you can create a module "projection" that will receive the previous objects to calculate the projections.
You can do the same thing for "depliage" function. Put that in a class that will receive a projected speckle..
Finally, you can also create a class "plot" to display the results.

Do not hesitate if you have questions.

**Comment by navylemdi** [comment]
Hi, the image and object class you want are the Feuille and Surface class. Or I didn't understood what you want to do. In my code, I don't need camera properties.
I updated my code with a new Plot class to make the code clearer. I also add "for" loop to navigate through all the speckle image.
Tell me if you see something else to change.

**Comment by navylemdi** [comment]
Hello, to avoid infinite speckle searching loop, I decide to put a limit of 100 speckles you can load in the program. 
Also to make the yaml easier to write I decided to remove the mandatory "/" from Path variable in yaml file. Now you just have to copy/paste the path of your speckle folder.
You can pull the knew code.

**Comment by navylemdi** [comment]
Hello, I added a 3D surface view to the 3D viewer. Also, I added a new Camera class to calculate the field of view of the camera used. Now a cone appears in the 3D viewer that represents the field of view. 
You can pull the new code
